readme.md

Fixes typo

---

package.json

Bump electron

---

browser.css

- Make a timestamp of unread message has different color from a read one
- Add hover effect when choosing people for new conversation
- Fix people list stacking border
- Fix for new class name (Seems like Facebook has changed some of them)

Fix some styling in dark mode

---

browser.css

Apply Dark Mode styling to popup dialogs

---

index.js
package.json

Tiny UI improvement for OS X.
Before:
After:

Set attach point for sheets to under the toolbar

---

browser.css

Ref #89 
I wasn't able to reproduce the error so this is a hopeful guess I targeted the right css.
But I did fix the transparency issue
Before:
After:

Fix messages forwarding modal

---

browser.css

Fix window dragging

---

readme.md

the cask core is now included with brew
:smile:

remove cask tap step

---

dark-mode.css

Fix invisible search dropdown selection indicator color

---

browser.js
menu.js
readme.md

Closes https://github.com/sindresorhus/caprine/issues/127

Cmd hotkey thread switch

---

config.js
index.js
menu.js
readme.md

Add menu option for Always on Top

---

dark-mode.css

The conversation search was unusable in dark mode. Now it uses the proper colors.

Fix dark mode conversation search

---

browser.css

Include OS specific UI fonts, plus additional opentype features and font rendering improvements.

Add native OS UI font stack

---

browser.js

fixes https://github.com/sindresorhus/caprine/issues/127 again

Fix conversation CSS selector

---

browser.css

The extra diff is the trailing whitespaces, which I have trimed as per https://github.com/sindresorhus/caprine/blob/master/.editorconfig
Fixes #166

Ligature fix

---

index.js

correct dpr cookie to screen scale factor
---
Fixes #172

Support retina display

---

readme.md

I've noticed this has happened across quite a few repositories, unfortunately 😢

Update readme.md to fix broken link on screenshot.

---

dark-mode.css

Found the class _13iv, and changed the background color.
Fixes #187

Fix the @name-popover in the chat input box in dark mode

---

index.js
package.json
readme.md

Confirmation before sending image via Cmd/Ctrl+V

---

dark-mode.css

Converting dark-mode.css to use css variables. Fixes #193 
Think I got all the colors that appear multiple times, but didn't bother to convert most of the ones that are only used once.

Use CSS variables

---

index.js
package.json

Set messenger locale based on user's locale

---

dark-mode.css

changed the gaming icon from this:
to this:
and made the message blurb darker
(it was already right for the format *message_blurb*,
now it's also right for *sender: message_blurb*)
old:
new:

Dark mode improvements

---

browser.css
browser.js
menu.js
readme.md

Fix #140 with feedback from review
This adds the functionality to toggle the sidebar with the list of conversations.
Shortcut: CTRL/CMD+SHIFT+S

Add support to toggle sidebar

---

browser.css

Exclude toolbar buttons from draggable region

---

browser.js
menu.js
readme.md

I like the insert GIF shortcut, I'd like one for insert emoji as well.

Add insert emoji shortcut

---

browser.js

Fixes #228. Messenger changed the layout of the settings menu so selectors had to be updated.

Fix conversation action shortcuts (mute, archive, delete)

---

dark-mode.css

Change background to the correct color

---

index.js

Fixes #280.
Removed whitelist since it is difficult to support other locales.

Fix calling for groups and other locales

---

index.js
package.json

Fixes #202.
Seems to be caused by window keeping focus, so we just have to unfocus before hiding on minimize to tray.

Work around Electron window focus issue

---

index.js

Workchat window title changed.

Fix Workchat Bounce/Blink/Badge

---

dark-mode.css

Fixes include:
- conversation search arrows
- message action & reaction buttons
- quick replies & carousels for FB bots
- new send cash feature
- creating new plan
- misc fixes of old bugs.
Closes #278
Closes #218

Various dark mode fixes

---

dark-mode.css

This commit fixes colors for event bar in dark mode.

Fix event bar colors in dark mode

---

dark-mode.css

This commit changes color of the message box text to light when the
conversation is blocked.

Changed color when blocked

---

dark-mode.css

Remove redundant background containing emoji

---

config.js
index.js
menu.js
readme.md

Added GUI option to start app minimized and removed CLI option.
Close #313

Add option to launch minimized

---

browser.js
menu.js
readme.md

This adds a keyboard shortcut to search in previous messages.
I think it makes sense to let this shortcut be Ctrl+F. Thus I changed "Find Conversation" from Ctrl+F to Ctrl+K.

Add search shortcut

---

browser.css

This should look nice now. :smile:
Fixes #405

Fix chat options padding

---

browser.css

Removed bottom white line that is visible in dark mode.
Fixes #384

Remove bottom white line in message box in dark mode

---

browser.css

Change selected conversation color

---

index.js

Fix locale detection

---

.gitignore
browser.js
index.js
readme.md
touch-bar.js

Open conversations from the Dock menu

---

browser.css
dark-mode.css

The preview of links is restored
Fix #455

Fix link previews

---

browser.css

Fix the story background and the text color in header and also hide the Messenger icon when the story is open.

Fix story colors

---

browser.js
dark-mode.css

Fixed color of options in preferences in dark mode and issue with
setting notifications preference.
Fixes: #498

Fix some preferences issues

---

dark-mode.css

Some description text in preferences has been added and this fixes the color of the text.

Fix dark mode in preferences

---

browser.js
menu.js

I changed the type of the menu item "Toggle dark mode" to the "Enable dark mode" checkbox.

Make the "Toggle dark mode" option a checkbox

---

browser.css

A few minor stylesheets for a very narrow window

Minor fixes for compact mode

---

index.js

Check update every 4th hour.
Related to #515

Check for new version more often

---

index.js

Fix Work Chat

---

package.json

Adding snap config and fixing issues regarding this PR.
---
Fixes #460

Add snap support

---

browser.css

Centered title

---

browser.js

Added as requested.
Closes: https://github.com/sindresorhus/caprine/issues/557

Make the login "Keep me signed in" checkbox checked by default

---

menu.js
readme.md

To easily switch chat environment easily

Add keyboard shortcut for switching between Messenger and Workchat

---

browser.js
index.js

Tray icons was not turning into `unread` state when new messages are
received. There was a bug for group chat photo because it uses
background image on div instead img tag. Also `updateBadge()` method was
inside if statement that is true only on darwin platform so tray icon
wasn't changed on linux/win32.
Closes: https://github.com/sindresorhus/caprine/issues/578
Closes: https://github.com/sindresorhus/caprine/issues/582
Closes: #594

Fix tray icon

---

dark-mode.css

Fix dark mode for the `Please Verify` view

---

config.js
index.js
menu.js

Implemented feature exit caprine on close click using checkbox in menu bar.
Closes: https://github.com/sindresorhus/caprine/issues/622

Add `Quit on Window Close` setting

---

readme.md

Related: 61e176ae62c5de2e2e79388321986cc5d2b9f7cc
#630

Document setting to close the app when the window is closed

---

index.js
menu.js
readme.md

Added custom styles feature. This feature is meant for power users and it uses a css file that is injected when Caprine starts.
---
Fixes #535

Add ability to customize the user interface colors and styles

---

browser.js
config.js

Added the status of the "Keep me signed in" checkbox as a setting that is stored between sessions.

Persist the "Keep me signed in" choice

---

touch-bar.js

Crop label on Touch Bar button

---

browser.css
dark-mode.css
menu.js
vibrancy.css

before/after
before/after
before/after
before/after

Login screen styling improvements

---

browser.js
index.js

See: electron/electron#10420
Tested on MacOS only. Would be great if anyone could confirm this change doesn't negatively affect the app on the other platforms (windows and linux).
Fixes #712

Work around vibrancy issue on macOS

---

css/browser.css

@sindresorhus I've removed the unrelated changes caused by prettier.
Fixes #368

Fix small graphical glitch on message header

---

css/browser.css

fix typo in the word 'mesage' --> 'message'
cheers

Fix comment typo

---

css/dark-mode.css

Fix "missed call" styling in dark mode

---

css/dark-mode.css

Fix description bot card color in dark mode

---

css/browser.css
source/browser.ts

Fix `Show Message Buttons` feature when switching conversations

---

css/browser.css

Fixes #707, The video was playing just fine, except you couldn't see it.

Fix playing videos from shared photos

---

css/browser.css

#584 I managed to reproduce this issue by resizing the app.

Fix preferences not launching on small window sizes

---

css/browser.css

Make setting dialog usable with small window sizes

---

css/browser.css

Revert compact mode message icons changes done in #521

---

source/browser.ts
source/index.ts
source/menu.ts

The only important one is the emoji tweak, fixes cropped native emojis.

Electron 5-related updates

---

css/browser.css

Partially fixes ​#878
Before:
After:

Fixes selected conversation background

---

css/browser.css

Partially fixes​ #878
Before:
After:

Fix duplicated unread notification

---

source/browser.ts

Resolves issue with settings menu / `cmd + ,` not working due to invalid selector. Working resolve for issue #911.

Fix settings menu

---

css/workchat.css

Hello @sindresorhus 
This is to fix  #929 . I brightened up both the logo and slogan to be more readable.

Brighten Workplace login in dark mode

---

source/index.ts

Two commits from way back that got lost.

Minor notification tweaks

---

.gitignore
css/dark-mode.css
css/vibrancy.css

Problem does not exists for everyone, maybe I've got new Messenger design?
Fixes #948

Fix white message bar

---

css/dark-mode.css

Fixes #927 
Edit: Also fixes `more`, `quick-reply` icons..
<b>Before</b>
<b>After:</b>

Fix dark mode UI issues

---

css/browser.css

Fix preference toggle when sidebar is hidden

---

css/browser.css

Fix "Show Message Buttons" for new Messenger UI

---

source/browser.ts

Fix the preferences window and other overlays

---

css/dark-mode.css

Dark mode tweak

---

package.json

See: https://docs.snapcraft.io/removable-media-interface
Fixes #973

Add “removable-media” snap plug

---

css/browser.css

As per @sindresorhus request in https://github.com/sindresorhus/caprine/pull/975#issuecomment-507060295

Hide settings icon

---

css/browser.css

Fix new conversation icon on narrow window size

---

css/dark-mode.css

To help the visually challenged like myself. Just lightened a shade and it now displays much better.

Make the message blurb in contact list more readable in dark mode

---

source/tray.ts

Fix missing tray context menu on Linux

---

css/browser.css

Additionally, to the fix, I grouped all sidebar related styles into one "section", so it's easier to maintain them. @sindresorhus if you like this approach, I could group the other ones as well...

Fix hiding own profile picture in sidebar

---

css/browser.css

@sindresorhus 	@CvX
Fixes draggable issue mentioned in #1010

Fix draggable region

---

css/browser.css

Fix conversation display on small window sizes

---

css/browser.css
source/browser.ts

@sindresorhus 	@CvX 
Either I have access to a new messenger UI iteration or the selector changed. I added this additional selector for the emoji picker.

Fix the emoji picker

---

source/index.ts

@sindresorhus 	@CvX 
Fixes #1030
Fixes #1026

Save window bounds after window resize

---

css/dark-mode.css

Fix react icon in dark mode

---

css/dark-mode.css

Fix styling for removed message in dark theme. Fixes #1017

Fix styling for removed message in dark mode

---

css/dark-mode.css

Fix dots color in dark mode

---

source/config.ts
source/menu.ts

Added an info alert when the user toggles on Auto Hide Menu Bar.
Fixes #1122

Show tip after enabling `Auto Hide Menu Bar`

---

readme.md
source/browser.ts
source/menu.ts

`Ctrl+U` seems to be used, could not make it work. Went for `Ctrl+T` instead.

Add `Attach files` menu item and keyboard shortcut

---

css/dark-mode.css

Fix display of right sidebar icons in dark mode

---

css/dark-mode.css

Fix Facebook Marketplace item in dark mode

---

css/dark-mode.css

Fix "say hi with a wave" in dark mode

---

source/index.ts

Display newest conversation at launch

---

css/browser.css

Fix new message icon alignment

---

source/menu.ts
source/util.ts

Fixes #1112 
Feel free to change the dialog text, it's not my mother tongue 😄

Add private mode confirmation prompt

---

css/browser.css

Fit image previews when resizing window

---

source/index.ts

[FIX] setDarkMode loop on macOS

---

source/index.ts

[Fix] Vibrancy issue on app refresh

---

source/browser.ts
source/browser/conversation-list.ts

Fixes #1185 
Closes #1234
Please have a look, thanks! 
cc @CvX @sindresorhus

[Fix] Emoji picker crashes app

---

source/config.ts
source/index.ts
source/menu.ts

fix https://github.com/sindresorhus/caprine/issues/209
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#209: Call sound should also be disabled](https://issuehunt.io/repos/42574339/issues/209)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

Add preference to mute call ringtone

---

css/dark-mode.css

Redo of #1372, sorry for the inconvenience.

Fix "Create new room" button in dark mode

---

css/browser.css

Fix private mode not hiding all private info

---

css/new-design/browser.css
css/new-design/dark-mode.css
source/browser.ts
source/browser/selectors.ts
source/menu.ts

This fixes `Search in Conversation` option. It wasn't implemented by Messenger website at the time of last release but since it is now, I'm adding the option back in for new design.

Fix Search in Conversation menu option

---

css/new-design/browser.css

- Change titlebar element (both name and picture)
- Read indicators (in group chats, the indicators that aren't the last one are controlled differently)

Hide additional attributes in private mode

---

css/new-design/browser.css
css/new-design/dark-mode.css
package.json

New design css was not being linted. This adds linting for it and fixes the linter errors.

Add linting for new design CSS

---

package-lock.json
package.json
source/constants.ts
source/menu.ts

Tested on Linux using both AppImage and .deb install methods.
Fixes #1435.
Fixes #1308.
Before:
After:

Improve about window information and icon

---

package.json

Fix Snap publishing

---

css/new-design/browser.css

Does not change wide sidebar mode.
Builds on #1652.

Fix hidden sidebar and narrow sidebar

---

css/new-design/dark-mode.css

Apply dark mode coloring to preference icons

---

css/dark-mode.css
source/browser.ts
source/browser/conversation-list.ts
source/browser/selectors.ts
source/emoji.ts
source/index.ts
source/menu.ts
source/types.ts

This PR completely removes ALL code related to Messenger's old design which was phased out in late 2020. It will for sure make debugging the project easier.

Completely remove old design code

---

css/browser.css

Remove new "Install Messenger app" banner

---

css/dark-mode.css

Fix search close button color in dark mode

---

css/dark-mode.css

…priate color for the time being
Closes #1932
@dusansimic

Fix attachment and receiver pill background in dark mode

---

.github/workflows/build.yml
.github/workflows/tests.yml

CI: Use setup-node action for caching

---

css/dark-mode.css

Fixes most icons on new Messenger UI.
Closes: #1935

Fix dark mode icons

---

source/browser.ts

Fixes the "New Room" button which stopped working on new Messenger UI.

Fix new room button shortcut

---

css/dark-mode.css

This PR removes some redundant and conflicting CSS and fixes the "Visit Group" button.

Dark mode fixes

---

css/dark-mode.css

Fix voice message duration text color in dark mode

---

source/browser.ts
source/browser/selectors.ts

Fix hidden dialog issue

---

source/index.ts

Fix open links issue

---

css/browser.css
source/index.ts

TODO:
Screenshots:
Closes: #1488 
Closes: #1857

Fix macOS ui

---

css/browser.css

Selectors have updated due to interface changes.

Update the "Messenger for Windows" CSS selectors

---

package-lock.json
package.json

Fix CVE-2023-5217

---

css/browser.css

Fix macOS drag region

---

package.json

Add system wide install option on Windows

---

source/browser/selectors.ts

Notifications seem to be working after updating this selector.
Closes: #2084

Update conversationSidebarTextParent selector

---

source/browser.ts
source/browser/selectors.ts

Hello. Changed/updated some selectors in order to fix the hidden dialog issue.
Fixes #2106.
Fixes #2100(?) (not sure about the camera part)
Fixes #2098.
Fixes #2096.
Edit: Fixes #2113.

Hidden dialog issue Fix

---

packages/rpm/caprine.desktop

Keywords to make desktop entry trivially searchable with some useful keywords.

Desktop entry keywords
