sindresorhus/caprine

menu.js
tray.js

Since app by default go to tray I think its nice to have quit option in file dropdown.
Also left click on tray does nothing and most users probably expect app to open.

Add quit option to app menu and open app from tray upon left click

---

browser.css

I changed some CSS in order to fix #55 . Here's what it becomes.
**Before:**
**After:**

Fix some text color in darkmode

---

index.js

This will probably fix #45 but I don't have Linux to test.
Tested on OS X and it prevents multi instancing via the command line.

Only allow a single instance of the app

---

browser.js
menu.js
package.json

Bump to 0.37.8 to fix #83 
Also use https://github.com/danhp/electron-osx-appearance as `app.isDarkMode()` and `platform-theme-changed` event got deprecated. Ref https://github.com/electron/electron/pull/5282

Bump Electron to 0.37.8 and fix deprecated methods

---

index.js

This is blatantly stolen from Slack's Windows app.
Before:
With the option turned on:
It follows native behavior in that if hidden, hitting `Alt` will show the menu

Add option to auto hide the menu bar

---

dark-mode.css

This should fix #105. I think the issue was some transparency affecting un-styled text in code snippets.

Fixed dark mode overriding code snippet color

---

index.js
readme.md

Fixes #64 
Added a support for a simple "-m" flag that will cause the app to start up minimized. 
I only tested this on Arch Linux. It should work for all linux distributions, and in theory on MacOS. 
Since there are no other command line options I wasn't sure if we should have a help/usage message or not

Add CLI flag to start app minimized

---

browser.js

Fixes for the shortcuts that weren't working since Facebook change their layout a bit.
Thanks @zebapy for raising the issue in #127.

Fix conversation selectors

---

readme.md

We got rid of the old domain because it mostly caused issues.

Fix name and link for Homebrew Cask in the readme

---

browser.css
dark-mode.css

Fixes #138 
- Used the blue from message bubbles with different opacity in
dark/light modes.
- Slight tweaked the color of the latest message subtitle, so it would be easier to read in light mode.

Improve highlight for selected conversation

---

browser.css

Found an issue with the "Edit Nicknames" dialog when there are multiple users in a group chat

Fix scrolling issue with "Edit Nicknames" dialog

---

index.js

Transparent windows aren't needed to get vibrancy to work. Windows must simply not have any backgrounds to them.
Previous change:
Fixes #183

Fix disappearing shadow on macOS

---

config.js
index.js
menu.js
readme.md

Add options to independently disable read receipts & typing indicators.
Fixes #186 .

Add option to disable seen/typing indicators

---

browser.js
index.js
readme.md

We can make use of overlay icons to display unread thread count in Windows, similar to how badge counts work in macOS & Unity. 
Since tray icons are hidden by default, this also eliminates the need for the user to pin the tray icon.

Add unread count and taskbar overlay icon for Windows

---

index.js

This should resolve #92. 
Currently, Messenger's calls blocks the window from closing while call is active. I'm not sure if we should override that behavior. Also dark mode doesn't propagate to the call window yet.

Fix sending and receiving voice/video calls from within Caprine

---

browser.js
menu.js
readme.md

Add a shortcut to launch GIF search <kbd>⌘</kbd><kbd>G</kbd>.
I wanted to additionally add shortcuts to cycle through the gifs but it seems it would require `electron-localshortcut` and might be overly clunky.
_Edit_: actually, I realized <kbd>tab</kbd>  and <kbd>shift</kbd><kbd>tab</kbd> works to cycle through the gifs, so one doesn't have to reach for the mouse after all.

Add insert GIF shortcut

---

index.js
readme.md

Disable Facebook link tracking

---

config.js
index.js
menu.js

Like bouncing dock icon on MacOs, it is a common feature on Windows to make window (and app icon in task bar) flashing.
This PR implements flashing when a new message is received and adds an option to disable it.
Default is true because it is default behaviour of all chat apps on Windows.

Add flashing window on message on Windows

---

package.json

Should solve https://github.com/sindresorhus/caprine/issues/202.
I published a twin [PR on electron-debug](https://github.com/sindresorhus/electron-debug/pull/50) that upgrade `electron-localshortcut` there too.
If you want, when you'll publish a new version of `electron-debug`, I'll do another PR here to bump `electron-debug` version too.
This way, we'll avoid `Caprine` dependencies on two different version of `electron-localshortcut`

Bump electron-localshortcut version to 2.0.0

---

index.js

On Windows, if user has activated AlwaysOnTop option, when pasting an image: confirmation popup  appears behind (and maybe not visible).
Changing this popup as a main window modal fixes this issue.

Fix issue with paste confirmation when AlwaysOnTop is activated

---

readme.md

Simply add information about the Preferences menu to the readme. I use a minimal window manager on Linux, so I have no menu bar, and therefore had to browse the source code to find the Preferences keyboard shortcut :)

Add Preferences keyboard shortcut to readme

---

dark-mode.css
workchat.css

This style isn't specific to workchat, instead it can be applied to darkmode.
Fixes #273

Add sender color style to group chat

---

browser.css

Overrides `text-align: left` that are applied when multiple names appear.
Fixes #291

Center names in titlebar

---

browser-call.js
index.js
package.json

Removes this pointless step and calls the person right away:
I think this step isn't needed, because I already expressed my intent to call that person by clicking on the button.
This PR is extracted from the Touch Bar work.

Call immediately when starting a audio/video call

---

dark-mode.css

In dark mode, some of photo info text is in dark color. This commit
fixes that.

Fix photo info color in dark mode

---

browser.js
config.js
index.js
menu.js
readme.md

This PR adds a checkable dock option with what the user can mute or unmute the app's notifications, so they don't appear, kind of like with the do not disturb mode on macOS.
Also refactors and fixes the show preferences mechanism, because if the preferences was open and the user opened it again, it stacked.

Add mute notification option

---

browser.css

The right-sidebar was kept opened in compact mode and it was difficult
to read messages. This fixes it and hides right-sidebar in compact mode.
Closes: https://github.com/sindresorhus/caprine/issues/350

Fix opened right sidebar in compact mode

---

dark-mode.css

Right sidebar menus where white from the light theme. With this commit
that is fixed.

Fix right sidebar menus in dark mode

---

browser.css

Video player width is fixed and it is not resized when the window gets
too small. This fix will resize it when window size is changed.

Fix video player width

---

dark-mode.css

This prevents the group conversation name from turning black while renaming the conversation.

Fix group-chat name text color in dark mode (#383)

---

dark-mode.css

I used the same text color used pretty much everywhere else in dark mode, not sure something else should be used.

Fix rich media integration name in dark mode

---

browser.js

When notifications are enabled the setting is not saved and on each
start of Caprine notifications are disabled. This fixes it.
Fixes: https://github.com/sindresorhus/caprine/issues/369
Fixes: https://github.com/sindresorhus/caprine/issues/381

Fix mute notifications not saved

---

dark-mode.css

Uses the container color as background color for the conversation contact list dropdown.
Fixes #397

Fix dark mode transparency issue with the conversation contact list dropdown

---

dark-mode.css

Fixed admin label next to members names in group chat so it's light in
dark mode.

Fix admin label in dark mode

---

browser.css
browser.js
config.js
index.js
menu.js

This commit suggests to hide options in message box (insert emoji,
image, git...) and show them with hover over like/send button. This
would make interface clean without removing those options.
Fixes #355

Add `Show Message Buttons` option

---

browser.js

This is a fix for long-time issue in Caprine. Mute notifications option will now be saved and set after startup again.
Closes #417
Closes #414

Fix mute notifications setting on startup

---

browser.js

Decrease the indentations to the left and to the right. Thus, the image area became more compact, which made it possible to slightly increase the resolution of the image
Before:
After:

Remove left and right padding in touch bar buttons

---

browser.js

Config variable `notificationsMuted` is true if notifications should be
muted, not unmuted. There was a bug in if statement in `browser.js` when
it checks config state and real state.
Closes: #437

Fix mute notifications

---

browser.css

Looks like Facebook changed the class names (they seem to be using some sort of build tool that renames classes) which broke app dragging (fixes #410). This PR adds the class name Facebook is currently using for the relevant element, and resolves the dragging issue.

Update class name for app drag region

---

browser.css

Fix the `New Conversation` button overlapping the traffic light controls on macOS

---

readme.md

electron-builder updated their docs, presenting the user with:
>Moved to [Multi Platform Build](https://www.electron.build/multi-platform-build) on [electron.build](https://electron.build/configuration/configuration) site.
This commit updates the link to point to the link the old wiki tells you to go to.

Update build docs link

---

dark-mode.css

Changed color of the timestamp in contact list so it would match all
other because the background color of contact is now used as an
indicator if messages are read or not, the blue color of a timestamp is
not needed anymore.

Fix unread conversation timestamp color

---

browser.js

The name of the function `isPreferencesOpen` and its use makes it think that it returns the boolean value.

The `isPreferencesOpen` function must return boolean

---

browser.css

I think it's a mistake to forcibly hide the right panel in compact mode.
This prevents users from accessing some important features, such as viewing attachments, discussion settings, and more.
It's best to leave the right panel visibility at the discretion of each individual user.

Don't hide the right sidebar in compact mode

---

browser.css

https://github.com/sindresorhus/caprine/issues/490
While the inline fix in Chrome worked, the Electron version needs an `!important` tag to override. Update to https://github.com/sindresorhus/caprine/pull/153

Update overflow scrolling rule to !important

---

.gitignore
browser.css

1. Fixed: when the window is very narrow then the text in the header overlaps with buttons
2. Fixed: when the window is very narrow then the buttons near the text box fall into two rows
Fixes #529

Fix a couple of visual bugs in compact mode

---

browser.js

Due to recent changes to preferences dialog and new options added order
of options was changed and that caused `Mute notifications` option to
change sound setting instead of notificaions setting.
Closes: https://github.com/sindresorhus/caprine/issues/519

Fixed sound/notifications option saving

---

browser.css

It's decided to hide mute notifications option from preferences since there has been a confusion should menu bar options be used or preferences option. Preferences option is not saved for next sessions like menu bar option is. This enforces use of menu bar option.
Fixes: https://github.com/sindresorhus/caprine/issues/498

Hiding mute notifications option from preferences

---

.gitignore
index.js

Previously, the change of the badge was dependent on the title of the window. Now the badge depends on the number of unreadable dialogs directly in the DOM.

Update badge on conversations change

---

readme.md

Caprine is available from the [community repository](https://www.archlinux.org/packages/community/any/caprine/).

Add installation instructions for Arch Linux to the readme

---

browser.js
menu.js
vibrancy.css

Since Caprine is now using Electron version 3, I wonder if the rendering bugs are gone and it is safe to re-enable vibrancy support for macOS users? I haven't noticed any graphical artifacts from enabling dark mode and vibrancy as of now, so I've submitted this PR in case it's okay to re-enable vibrancy.
I've also added some selectors to make the chat's title bar and the shared link's preview transparent.

Re-enable vibrancy support for macOS users

---

config.js
index.js
menu.js

There is some demand to disable hardware acceleration to prevent electron from kicking GPUs into high-performance modes (effectively using a lot more energy).
This change adds a new menu option that toggles a config value to disable the hardware acceleration. By default, the hardware acceleration is enabled to stay parity with the current behaviour.
-----
There is some concern around rendering artifacts as mentioned in #469, although some reports are indicating with the recent build they aren't present.
---
Fix #469

Add an option to disable hardware acceleration

---

index.js

Fixes #288
I'm proposing to change the app's macOS close window behaviour to be the default behaviour for closing macOS apps, which uses `win.hide()` instead of the "hide behaviour" (<kbd>Cmd</kbd><kbd>H</kbd>), which uses `app.hide()`.
I realize that this was an intentional change, and I saw the issue you opened in the Electron repo [here](https://github.com/electron/electron/issues/3694). However, I think this should be reverted for the following reasons:
1. It causes problems with window managers such as [Amethyst](https://github.com/ianyh/Amethyst). As described in #288, when using Amethyst, closing and re-opening Caprine doesn't re-render windows properly.
2. The default behaviour of all macOS apps is to have the "close behaviour" when closing an app, and the "hide behaviour" when …

Change close window behaviour on macOS to the default behaviour instead of hide

---

dark-mode.css

Decline button is now using more visible color in dark mode as recommended.
Closes: https://github.com/sindresorhus/caprine/issues/619

Fix decline button in dark mode

---

browser.js

Fixes #633
I'm running Caprine on Mac, and I have not experienced the white flash issue personally, but it might be an issue on other platforms. Since right now vibrancy is a macOS-only feature, I find it enough to simply apply the white flash fix if Dark mode is enabled, but not vibrancy.

Fix dark mode + vibrancy not rendering properly on restart

---

browser.js

Fixed a bug where notifications have no title in group conversations.
Fixes #626

Fix notification title for group chats

---

index.js

Caprine does not set the urgency hint for its window under Linux when a new message is received. This issue was discussed before (https://github.com/sindresorhus/caprine/issues/435). The provided change enables this behavior. Has been tested on linux (Arch + i3wm).
---
Fixes #435

Fix window flash on Linux

---

browser.js
index.js
notifications-isolated.js

Electron’s context isolation is preventing any `window.Notification` modification done by the preload script (`browser.js`).
This change works around that limitation by first injecting custom `window.Notification` in the main process using `webContents.executeJavaScript` and then by passing messages between browser context (Messenger code) and the Isolated Context (Caprine’s `browser.js`) via `window.postMessage/window.addEventListener('message', …)`.
As a bonus, this PR adds support for `onclick` and `onclose` Notification events used by Messenger. That allows us to remove `selectConversationByImg`, since Messenger selects the conversation in the `onclick` callback! 😃 
Fixes #700

Fix notifications

---

browser.js

Currently, composing a new message breaks causes Caprine to throw an error, since it tries to get a conversation image when there's none. Just skipping the image part doesn't cut it - "New Message" shows up on the Touch Bar, but tapping it doesn't do anything and tapping any conversation selects a different one (off by one).
For now, this PR only avoids the error by not trying include the "New Message" in the Touch Bar.
Eventually it would be nice to have it there, together with the ability press cmd+1 to select it, but that requires quite a lot of changes to conversation selection code.

Fix Touch Bar when on the "New Message" view

---

browser.js

Gets rid of the preferences dialog flash on startup and when changing the “Mute Notifications” setting.
**Application startup**
before/after

Hide the preferences dialog during the automated action

---

browser.css
dark-mode.css
vibrancy.css

**“Chat bot conversation start” element styling (a694838)**
**“Typical response type” styling in dark mode (3bdf8a7)**
**Vertically align “conversation info” buttons (11f1fba)**
before/after
**Prevent content shift on hover in “new conversation list” in dark mode (330ebbf)**
before/after
**Improve text contrast on message popovers (4153104)**
before/after
**Improve sticker search input styling in dark mode (74123fb)**
**Button styling throughout the app (d7fcff6)**
before/after
before/after

Various styling fixes

---

config.js
menu.js

Dark mode option is disabled on non macOS systems since `followSystemAppearance` config value is always true by default when it should be true by default only on macOS.
Closes: https://github.com/sindresorhus/caprine/issues/733

Fix dark mode being disabled on non-macOS systems

---

browser.css
browser.js

Fixed archive conversation issues. Now when a conversation is archived, it automatically switches to the next conversation so there wont be an empty display. Also with this PR fixed the issue with archiving group conversations.
Closes: https://github.com/sindresorhus/caprine/issues/590
Closes: https://github.com/sindresorhus/caprine/issues/591

Fix archive conversation issues

---

package.json

There’s no need to run them after each commit, and the time needed to launch tests each time adds up. It also prevented temporarily committing unfinished code, made it difficult to rebase commits, etc.

Run tests on push instead of commit

---

browser.js

To persist keepMeSignedIn checkbox state, detects changes using onChange event instead of onClick event.
Handles case when checkbox is (un)checked using keyboard.
Improves #698 which fixes #640.

Support persisting `keepMeSignedIn` toggled with keyboard

---

source/emoji.ts
source/index.ts
source/menu.ts
source/tray.ts

Fix static images paths

---

source/index.ts

Today I notice that old emoji styles does not work on my second PC (on first it still works). I looks like facebook sometimes fetch emoji from other domain. I created wildcard on subdomain to fix this problem.

Fix emoji style URL (add wildcard)

---

source/browser.ts

Closes #779 (or at least workarounds some of the issues described there)
It seems that either Messenger is rolling out or A/B testing some document structure changes or we have a bug that affects only some Caprine users.

Add a fallback for missing uiContextualLayerPositioner

---

source/config.ts

Caprine on non-macOS platforms could have had their `vibrancy` config value set incorrectly to `full` or `sidebar`.

Make sure the vibrancy is enabled only on macOS

---

package-lock.json
package.json
source/ensure-online.ts
source/index.ts
source/p-wait-for.d.ts
source/util.ts

@sindresorhus ,
Hello!
This PR should fix the initial app launch issue with network connectivity and also allow for `Caprine` to be launched on system start/login without the need of a manual refresh. (Fixes #421)
Any feedback is welcome. Thanks!

Handle initial network connectivity

---

source/config.ts
source/index.ts
source/menu.ts

Closes #699 
Added as an option inside `Caprine Preferences`.
Let me know if anything needs to be changed.
I've tested this on macOS Mojave (10.14.2).

Add option to block delivery receipts

---

css/dark-mode.css

Just a minor css tweak to fix poll title text color in dark mode.

Fix poll title color in dark mode

---

package.json

Camera doesn't work for me when installing from the snap store, and it looks like the reason is because it doesn't have permissions. The [old workaround of `snap install --classic`](https://github.com/sindresorhus/caprine/issues/568) no longer works as of `snapd@2.36.2` ([relevant PR](https://github.com/snapcore/snapd/pull/6039)). 
Reading the relevant docs for [electron-builder](https://www.electron.build/configuration/snap) and [snap](https://docs.snapcraft.io/interface-management/6154), it seems like the right solution is to use the default confinement model and to explicitly specify a `snap.plugs` that includes `camera` in the `electron-builder` config.

Add `camera` plug to Snap build config

---

css/browser.css

Shared videos had bars on left and rights side. Removing this old fix
stops that behavior.
Closes: https://github.com/sindresorhus/caprine/issues/805

Remove shared video bars

---

source/index.ts

I was having an issue where navigating to something like `prod.messenger.com` would open in my browser. I'd like to be able to do that in the Caprine app, so I changed the navigation rules to allow any hostname that contains `messenger.com`.

Allow navigation to alternate messenger domains

---

css/browser.css
css/code-blocks.css
css/dark-mode.css
css/vibrancy.css
package.json

Stylelint wasn't run on `npm test` (regression introduced with TS migration). My bad.

CSS tweaks

---

source/index.ts

Fix error on quit caused by Electron race issue

---

css/dark-mode.css

Makes dark mode placeholder text in the nickname dialog match placeholder text elsewhere (e.g. "Add People" dialog).
Closes #857

Fix dark mode style for nickname dialog placeholder

---

source/index.ts

This seems to fix #845 for me.
Built and tested on Linux.
Redirects are as follows:
* work.facebook.com (initial page loaded by caprine)
* work.workplace.com 
* companyname.workplace.com
More info on the domain switch: 
* https://www.facebook.com/help/work/1116975388401705?helpref=hc_fnav
* https://www.facebook.com/workplace/resources/deepen/prepare-community-workplace-domain

Support the workplace.com domain

---

css/browser.css
css/dark-mode.css
source/browser.ts

Fixes #702, when the window is inactive / blurred, the open chat changes to gray in the contact list. When the window is refocused, the open chat returns to blue in the contact list.
The selected state when the window is active (also the original "inactive" window state):
Inactive window for light mode:
On dark mode:

Add contact list styling for inactive window

---

source/browser.ts
source/browser/conversation-list.ts
source/browser/selectors.ts

Fix missing unread badge

---

css/vibrancy.css

Partially fixes​ #878
Before:
After:

Remove unnecessary lines between items on the conversation list

---

css/vibrancy.css

Partially fixes​ #878
Before:
After:

Fix too strong chat title bar bottom border

---

css/browser.css
source/browser.ts

Fixes #831 
@sindresorhus 	@CvX 
Issue is pretty much explained [here](https://github.com/sindresorhus/caprine/issues/831#issuecomment-498070981) by @CvX 
Explanation: Triggering `mouseover` fetches the popover module. When switching conversations, the emoji component unmounts and needs `mouseover` in order to function correctly with the keyboard shortcut.`Mutation Observer` is clunky and heavy on performance since we can't listen directly on the node we require. Polling is also unreliable.
I think this one is consistent & the most performant. Please have a look.Thanks!
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#831: Bug with emoji selector](https://issuehunt.io/repos/42574339/issues/831)
---
IssueHunt has been backed by the …

Fix emoji picker

---

css/browser.css
css/dark-mode.css
css/vibrancy.css

Problem does not exists for everyone, I've got new messenger version only on one device.

Fix white plus bar, removed report bug icon

---

source/browser/selectors.ts

@sindresorhus 
Fixes #765 
The scrollbar from the conversation list has a weird behaviour when the `zoom` property is applied on the parent container.
I could not reproduce this in a separate environment. It may be related to `electron` and/or `messenger`.
The workaround is to apply `zoom` on the content (without the scrollbar).I've also updated the `conversationSelector` with a fallback.

Fix dragging scrollbar when app is zoomed

---

source/config.ts
source/index.ts
source/menu-bar-mode.ts
source/menu.ts
source/tray.ts

Fixes #684 
@sindresorhus 
I've closed the previous PR, had some issue with those commits, #800 
To summarize:
- Added `Show Tray Icon` menu item, Defaults to `true`
- If `quitOnWindowClose` is `true` or `showTrayIcon` is `false`, don't create tray or `destroy()` already created tray
Thanks!

Add setting to hide the tray icon

---

css/browser.css

This PR supposed to fix the issue when FB needs to re-authenticate you due changed location. That happened to me today. Unfortunately I am not able to force FB to do it again, so can't test it after restoring the app.

Fix Facebook logo placement

---

css/dark-mode.css

I think `-webkit-text-fill-color` is required on macOS electron apps, it looks like. Adding this rule fixes the issue. This should fix #1001, at least on macOS
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>

Set placeholder text to the correct color on macOS when in dark mode

---

source/config.ts
source/ensure-online.ts
source/util.ts

@sindresorhus 	Fixes #1031
I could not reproduce #1034, I've checked and all enum values are valid. It might be that the config file was edited/corrupted/had old values before the schema was introduced which would explain an app crash. Should be fixed by a clean install / config reset.

Fix schema validation crash

---

css/dark-mode.css
css/vibrancy.css

Improve the dark mode in the login flow

---

readme.md

Pressing "Alt" will toggle the menu bar in (at least) the most common desktop environments. Fixes #208.
Simple change to Readme.

Document that Linux supports `Alt` to toggle menu bar

---

source/index.ts

This PR tries to work around the vibrancy issue.
Vibrancy effect is still missing:
- when docked Dev Tools are present
- in a brief time window (~3 seconds) after a navigation/reload
Before/After
Closes #1056
Closes #1052
Closes #712

Work around the vibrancy issue

---

source/browser.ts

I have a cropping issue (emojis are rendered too far up) when using my system font, ttf-joypixels on Arch Linux. This change fixes it for me, but I'm not in a position to test if it breaks things for other systems/font packages.

Improve cropping for system emoji on some Linux systems

---

source/browser.ts

Seems Messenger has been updated.
"Insert Emoji" and "Insert GIF" seem to have broken.
Here are fixes :raised_hands:

Fix keyboard shortcut for "Insert GIF"

---

source/config.ts

Fix #1079 
If the vibrancy does not exist in the config it never set.

Check the vibrancy config is existing

---

css/browser.css

Fix the GIF search field background

---

css/browser.css

Fixes group image stretching when width of window is small.
Resolves #1116 
Before: image sizes down because it has set just width and height. But when window sized down, image stretch badly.
After: image remains same size when widnos sizes down

Fix group avatar being squished

---

css/dark-mode.css

Fixes #1103 unreadable text in group settings.
**After**

Fix "require admin approval" dark mode

---

readme.md
source/browser.ts
source/menu.ts

The selector for the "Insert Text" keyboard is not specific enough, it focuses the wrong textbox some times (for example when having the "search" feature open in a group chat).
* I've made the selector more specific.
* I also renamed "Insert Text" to "Focus Textbox" https://github.com/sindresorhus/caprine/pull/1014#discussion_r310539228
* I chose "Focus Textbox" over "Focus Text Input" for brevity. Can rename if wanted.

Fix "Insert Text" keyboard shortcut

---

css/dark-mode.css

This introduces some dark mode style consistency fixes. The changes are:
* dark background behind reaction in reaction popup
* light icons in Sidebar > Options menu
* dark background on hover in Sidebar > Edit group picture
* removed white border on profile pictures
* dark "replied to" label on message replies

Fix some dark mode styles

---

readme.md
source/menu.ts

Was happy to see v2.40.0 released, with the new "Attach Files" keyboard shortcut :smile: Good work :beers: 
Was eager to try "Attach Files", and it works, though not well.
`CommandOrControl+Shift+A` requires two presses before activating at my system. I'm guessing that the key combination conflicts with something.
I'm proposing to change it to `CommandOrControl+T` to make it work in one key press. Any other combination is fine as well, as long as it works.

Fix "Attach Files" keyboard shortcut

---

css/dark-mode.css

Resolves #1132 
When Facebook account is disabled you can still use messenger, but the name is not <a> so it looks bad in dark mode.

Fix disabled contact name in dark mode

---

css/dark-mode.css

I found that all icons in group chat on the left side before notification has this xpath "._497p ._uwa". So I inverted all of them, because facebook icon sprite can change anytime and searching white on each icon would be lot of work with every sprite change.
Resolves: #883 
after:

Fix group notification icons in dark mode

---

source/menu.ts
source/tray.ts

It fixes bug on linux with KDE Plasma that after toggling to and from tray 'Always on Top' setting stops working despite it is still checked.

Fix `Always on Top` after tray toggling on KDE Plasma

---

source/index.ts

Closes #1140 
@CvX @sindresorhus 
Using [app.hide()](https://electronjs.org/docs/api/app#apphide-macos) on `macOS` gives focus to the previous window.

Fix focus when closing app on macOS

---

package-lock.json
package.json
source/emoji.ts
source/index.ts

I was complaining about a system vibrancy problem in #1091 and it was indicated that to fix the issue properly on Catalina it was necessary to wait for the next version of Electron to be released. It was indeed released a week ago.
This PR updates the version and then fixes the errors that I saw running `npm install && npm start`.
(It does not appear to fix my original complaint, any additional work will go in another branch)

Update to Electron 7

---

css/browser.css

Limits photo, video, and GIF widths so they don't overflow horizontally. Also shuffles around UI for inline event previews:
becomes
This is similar to the changes in PR #861 (closed unmerged) and fixes #851, fixes #859, and fixes #1066.

Resize media and embeds for narrow windows

---

css/browser.css
source/browser.ts
source/config.ts
source/menu.ts

Adds the ability to change between different sidebar widths (fixes #297). Let's you choose between:
* adaptive (default, changes with window size)
* hidden (same as before, hides sidebar completely, fixed to move group text title out of the way of MacOS traffic lights)
* narrow (force narrow-screen sidebar on all window sizes)
* wide (force wide-screen sidebar on all window sizes)
I wasn't sure on how to keep the toggle sidebar keyboard shortcut, so I made the menu item to hide the sidebar act as toggle. This might be unconventional, let me know if there is a better way.

Add ability to force sidebar width

---

css/browser.css

After #1167 360 photos don't have minimal width and height.
So I removed 360 class from being set width|height = auto !important.

Fix hidden 360 photos

---

css/dark-mode.css

Fixed issue where the person list item text color was being applied with `color: var(--base-seventy);`. This should fix the issue in any popups displaying the same list item as well.
Tested on Windows 10.
Before:
After:

Fix issue where people list item color was not selected

---

source/index.ts

…lose is enabled.
System: Windows 7
Fixed Problem: 
I've noticed that when Quit on Window Close option is enabled tray icon is not showing after restarting the application.
To reproduce the problem, set:
File->Caprine Settings->Show Tray Icon on true
File->Caprine Settings->Quit on Window Close on true
then close applications and open it again. The tray icon is not showing.

Fix a bug that prevents the tray icon from showing

---

source/browser.ts

Fixes #1027 
Right now, the “Hide conversation” menu item (AKA the archive button) does not work. This was because of some CSS selectors seem to have become outdated. I have replaced them as follows:
1. `.uiLayer:not(.hidden_elem) ._54nq._2i-c._558b._2n_z` → `.uiLayer:not(.hidden_elem) [role=menu]`
1. `${selectedConversationSelector} ._5blh._4-0h` → `${selectedConversationSelector} [aria-haspopup=true] [role=button]`
Note that the new selectors do not rely on minified class names like `_5blh` but rather on descriptive attributes like `[role=button]`. Hopefully, this means that these new selectors will be less likely to break with changes made to the Messenger website by Facebook.
Note also that I have tried to avoid using any localized attributes, so hopefully this works for all …

Fix “Hide conversation” menu item

---

source/browser/conversation-list.ts
source/touch-bar.ts

Take a look at https://github.com/sindresorhus/caprine/issues/1257 for more context.
The basic issue was that the **conversations** event was being sent only in cases when private mode was not enabled. This was fine for the majority of cases, but led to a bug in the notification badges not showing up.
This is a proposed fix where I refactored the logic to just always fire the conversations event and just have the Touch Bar component handle the display logic - looking back, this makes much more sense, and I'm embarrassed that I didn't implement this the first time 😅
Thanks @danielfbnunes for pointing this out!
Fixes #1257

Fix badge notification bug when private mode is enabled

---

package.json
source/browser.ts
source/browser/conversation-list.ts
source/emoji.ts
source/index.ts
source/touch-bar.ts
source/util.ts

As @sindresorhus mentioned in an issue https://github.com/sindresorhus/caprine/issues/848, Caprine should use [`electron-better-ipc`](https://github.com/sindresorhus/electron-better-ipc) so code would be more simple and readable.
Not a lot of code was removed but some unnecessary event listeners were removed because of `electron-better-ipc` features for sending and receiving data in a single emit.
An important thing to check would be the refactoring of the [`renderEmoji()`](https://github.com/sindresorhus/caprine/compare/master...dusansimic:add-electron-better-ipc?expand=1#diff-42884126f5a9ea114868102427dd7a72R234) function in `emoji.ts`. A lot of code is removed there since all the checks done by that function are actually implemented in `electron-better-ipc`. By that I mean that the if …

Use `electron-better-ipc` instead of the built-in IPC

---

source/config.ts
source/menu.ts

Resolves #1186 
I have already looked at this problem before but Electron had a bug with the checkbox. electron/electron#21159
I had to use async function because sync doesn't return information if the check was checked or not.
Also when you once check the check you have to 'Debug->Delete settings' if you want to see dialog again.

Add remember option checkbox in private mode dialog

---

source/browser.ts
source/config.ts

Fixes #1305
Summary:
- The issue was that the config would always be overwritten for those who didn't have the `sidebarHidden` key to always `default`.
- After setting the new migration key, we should also delete the old one so we don't reset it to `hidden` every time.
- I've also deleted a IPC call that looks out of place.
cc @sindresorhus @CvX

Fix the sidebar config migration

---

source/index.ts

Workaround electron's location handling on new windows [window.open()]
Fixes #1189
I also described the full solution in my [comment](https://github.com/sindresorhus/caprine/issues/1189#issuecomment-609765491) on the issue. 
> - Doing newWindow.location = "/path" fails because at it seems, by default electron is trying to join the new-window's location (that window's window.location) with the new location (/path), but the new-window doesn't have valid location.href because it wasn't opened with one.
>     `w1 = window.open() // w1.location.href === "about:blank"`
>     In normal browser, as long as your new location is not valid URL on it's own (?) it would join the new path with current's window (the window from where you are opening the new-window) location, not the new-window's one.
> …

Fix making and receiving calls

---

source/config.ts
source/index.ts
source/menu.ts

The spell checker can be quite annoying at times, so I've added an option to Caprine's preferences to configure whether it is enabled.
I couldn't find a good way to update the BrowserWindow webPreferences option during runtime, so unfortunately a restart is needed to configure the spell checker.

Add option to disable spell checker

---

source/browser.ts
source/index.ts
source/menu.ts

If the show unread badge option is toggled then sends a reload action to browser to refresh badge fixes #1355 . Also updates index.ts updateBadge to remove the badge overlay icon if config.get('showUnreadBadge') is false.

Fix unread badge not always updating

---

source/browser.ts

This completes the requested changes in https://github.com/sindresorhus/caprine/pull/1295. It's basically the same PR and most of the code is from @fbianconi. I've made this since there hasn't been a lot of activity on this issue for some time and I wanted to get it fixed.
Closes: https://github.com/sindresorhus/caprine/issues/1278

Fix autoscroll on new messages

---

source/index.ts

FB changed their 2FA login url. Without this change, Electron will open the 2FA login page using external browser.
Fixes #1415
Fixes #1414

Fix 2FA login issue

---

css/dark-mode.css

Minor dark mode style fixes:
Closes: #1155

Fix dark mode

---

css/browser.css

Scroll bar was being hidden due to an old bug on Windows. This would make it hard to scroll in the message box of there was a lot of text.
Closes: #1223

Fix scroll bar in message box

---

package.json

Add fix for Windows app icon. This fixes the icon being cut in half and bad resolution of the icon. The solution for this issue was found here https://github.com/electron-userland/electron-builder/issues/2128.
Closes: #1429 
Closes: #1453

Fix Windows icon

---

source/browser.ts
source/index.ts

Since Facebook is rolling out new Messenger design, some users have it and some user don't. This adds logic for dynamically switching css that is injected based on users Messenger design.
This is being added as a PR so contributors could use this for implementing broken features on the new design.

Add switch logic for Messenger UI

---

css/new-design/dark-mode.css
source/browser.ts
source/index.ts

Enable Facebook dark mode when option is turned on and add patches to the integrated dark mode.
Closes: #1452

Fix dark mode on new Messenger UI

---

css/new-design/browser.css

There is a disabled scroll bar on the right side of the app window.
Since it is disabled, it can't be used to to scroll anything and it's
basically useless. This just hides it from view so it won't get in the
way of using the app.

Hide disabled scroll bar

---

source/browser.ts
source/browser/selectors.ts

This fixes shortcuts not working for non US locales on new UI. This problem has occurred because query selectors relied on locale based `aria-labels` which didn't work on locales other than US. This is fixed by using class names and other attributes instead of `aria-labels`.
Closes: #1544

Fix shortcuts on non-US locales

---

css/new-design/browser.css

This fixes private mode on new design. It blurs following items:
* Chat list: profile picture
* Chat list: conversation name
* Chat list: last message
* Conversation: profile picture
* Conversation: name
* Message list: profile picture
* Message list: reply label
* Message list: sender label in group chat
* Message list: tiny heads
* Right sidebar: profile picture
* Right sidebar: name
This is the final result:
Closes: #1492
Closes: #1555

Fix private mode on new design

---

css/new-design/browser.css
source/browser.ts
source/index.ts

This PR adds a boolean flag for the `updateDoNotDisturb` and `openHiddenPreferences` functions, to prevent the preferences window from opening on startup. I know its not the best solution, but gets the job done for now(:
fixes #1547

Fix preferences opening on startup

---

css/new-design/dark-mode.css

Some dark mode styles won't work on different locale since they rely on aria label attribute which relies on locale. This would fix that problem. Also fixing mute icon color in dark mode.

Fix dark mode style on different locale

---

source/browser.ts
source/browser/conversation-list.ts
source/browser/selectors.ts
source/menu.ts

This would fix tray indicator for new messages, however there is one problem. The problem with excluding muted conversations from unread conversations is that once you get a new message in muted conversation, you lose the muted icon. The only way the to check if the conversation is muted is to open muted is to open conversation menu and check if there is an unmute button. The problem then arises when the user has already a different menu open which will result in closing of that menu. Because of that we cannot check if conversation is muted without causing unexpected behavior. Any thoughts on this issue are very welcome!
Closes: #1536
Closes: #1028

Fix conversation list on new UI

---

source/browser.ts
source/menu.ts

This fixes dark mode not being set on startup. Messenger website seems to remove the `__fb-dark-mode` class from root element when website loads completely which is right after Caprine adds the class. This disables dark mode on startup event if it's enabled.
This solution uses MutationObserver to monitor for changes in class list of root element and check if weather dark mode classes are present. If Caprine dark mode config and class list don't match, Caprine will set dark mode classes again. This sets dark mode automatically on startup when it's enabled.
Closes: #1525 
Closes: #1538

Fix dark mode not being set on startup

---

readme.md

Add installation instruction for Fedora. I've created an RPM build with COPR (a build system for rpm packages) which also creates a repo for the rpm. Now Caprine can be easily installed on Fedora.

Add Fedora install instructions

---

source/browser.ts

There were some minor ui changes that caused next and previous conversation shortcut to stop working. This is now fixed.

Fix next and previous conversation shortcut

---

source/util.ts

Like https://github.com/sindresorhus/electron-util/pull/47, this change puts the Restart Dialog on top of the current window.

Show restart dialog on the current window

---

source/emoji.ts

Very minor fix, but should address one "TODO" marking. In my testing (on Linux), I was able to switch emoji types with no errors/warnings.

Improve a type annotation

---

source/index.ts

Disables the warning for more than 4 parameters in an async arrow function, despite Electron using one with 8 parameters in https://www.electronjs.org/docs/api/web-contents
```javascript
myBrowserWindow.webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures, referrer, postBody) => {
}
```

Disable ESLint max-params for async arrow function

---

css/new-design/dark-mode.css

This fix was provided by @nforro in #1604. It removes the top gap in dark mode. This fix should be removed once Facebook fixes their dark mode css.
Closes: #1604

Fix top gap

---

css/new-design/browser.css

The css for creating dragable region on macOS should only be enabled on macOS. This disables it for all other platforms.

Create draggable region only on macOS

---

.github/workflows/main.yml
package.json

So far main workflow would test and build Caprine for Linux, macOS and Windows on macOS platform which would result in bad checksums. Also tests sometimes break for no reason at all.
The main difference here is that build and test jobs are split and build process is run on respecting platform for each package. This doesn't break the checksum. This can be seen in action in [playground](https://github.com/dusansimic/caprine-playground) repo.
Aditionally, everything is published automatically, including the snap package.
Closes: #1563 
Closes: #1554 
Closes: #1163

Refactor GitHub Actions

---

css/new-design/browser.css

This fully eliminates the banner advertising the Messenger App for Windows. Perhaps we may not want to remove it entirely, but if someone is using Caprine, they probably want to stick with it.
Regardless, the banner gets a bit mangled with the narrow sidebar:
The wide sidebar shows this correctly: 
Another possibility would be to remove the banner when the sidebar is narrow, but keep it when the sidebar is wide?

Hide banner for Messenger App for Windows

---

source/index.ts

The linting applied in #1628 removed some empty files in `css/new-design`. We do a simple `existsSync()` to ensure that the file exists before applying its CSS.

Check that CSS file exists (for new design)

---

source/index.ts

The change in #1630 did not check for the *full* path. This was causing none of the CSS files to be read, since they don't exist in the `source/` directory.
Also, there was not a check for the `workchat.css` case. Now all of the `insertCSS` blocks have the same structure.

Use full path to check that CSS file exists

---

source/browser.ts

Even if dark mode was set, new nodes (dialogs, etc.) would appear with the `__fb-light-mode` tag, which breaks the theming. I've set up an observer for added nodes and only change ones that have some sort of light mode tag.
This may not be the best or most efficient way to do this, but it seems to apply to most dialogs that I was able to find: Preferences dropdown and overlay, emoji picker, etc.

Apply dark mode to all new nodes

---

css/new-design/browser.css
source/browser.ts

Going along with the changes in selectors in #1629, the Preferences overlay was not being selected properly (and would raise an `UnhandledPromiseRejectionWarning`). In addition, the `subtree: true` can be removed from the `observe()` function.

Fix preferences selector

---

source/browser.ts
source/config.ts
source/index.ts
source/menu.ts

The `api.nativeTheme` should work for non-MacOS platforms. This PR combines the `followSystemAppearance` and `darkMode` settings into a `'theme'` configuration setting, which mirrors the `api.nativeTheme.themeSource` variable. However, setting the `'dark'` or `'light'` mode should override the system settings.
I'm not sure if removing the `darkTheme`, which is supposed to force dark mode with _some_ GTK+3 environments, is okay. It could cause some issues with those environments that rely on this configuration.
The theme only updates when you click on the window, but I don't think it should be constantly checking while Caprine is in the background.
Tested on:
- Windows 10, build 19042
- Linux Mint 20.1, Cinnamon DE

Combine system appearance and dark mode settings

---

source/browser.ts

This check was missed in #1637. However, this might not even be necessary any more? I did some testing with Dark, Light, and System Appearance, and there were no flashes of incorrect colors with this section commented out.

Eliminate check for `darkMode` setting

---

source/browser.ts

Following along with #1632, this removes a locale-specific `aria-label` when deciding on whether to remove the `hide-preferences-window` class.
These should probably be abstracted to the `source/browser/selectors.ts` file instead of defining these selectors in the header of `source/browser.ts`.
Fixes #1645,
Fixes #1579.

Fix preferences selector for removing hide-preferences-window class

---

source/index.ts

Image addresses do not have tracking information on them, so there's no need to apply `stripTrackingFromUrl` for these links.
Fixes #1662.

Add option to copy image address

---

source/tray.ts

The function `getIconPath()` exists for a reason, so this implements it in the `tray.setBadge()` function.

Use getIconPath() in tray.setBadge()

---

css/new-design/browser.css

This is done automatically for pictures, but videos are a static size normally (501 px). If the window gets smaller than that, the video will scale with the max. width of the conversation.
[I tried to make an additional scaling for the height, but ran into more issues. The height of a picture/video is set by the width, it seems. Also, the height of the conversation "box" is much larger than is actually visible (to contain cached conversation items), so calculating with percentages or `vh` is more complicated than expected...]
Fixes #1631.

Scale videos down to max width

---

source/config.ts

The `darkMode` setting was replaced by `theme`, but the configuration file was not updated accordingly.
I believe that `'system'` should be the default, but I wouldn't want to force it on everyone who may have had `darkMode` set for specific reasons. This migration honors any previous configuration with `darkMode`.

Migrate `darkMode` settings in config file

---

css/new-design/dark-mode.css

Messenger website is adding `__fb-light-mode` class to an element in received messages which makes message text dark instead of light in dark mode. This is fixed by setting the `--primary-text` variable to a light color from dark mode in `__fb-light-mode` class only if said class is in a child element of an element containing `__fb-dark-mode` class. This way, the style is applied only in dark mode.
Closes: #1672

Fix received messages color in dark mode

---

source/browser.ts

This stops the checking for the new design on the DOM ready event. This is necessary to continue the code in `source/index.ts` for the old design, and also for when the user is not already logged in (when the "new design" class does not exist yet). After login, the checks will happen again for the new design. It is unlikely that Messenger would change designs after the DOM ready event.
Fixes #1613.

Stop checking for new design on DOM ready

---

source/config.ts
source/menu.ts

Since Ctrl+Shift+T is used for many other things in other programs, it could be helpful to show a prompt when the keyboard shortcut is triggered.
Fixes #1286.
Prompt on Linux:

Display prompt for Always on Top setting

---

source/spell-checker.ts

While adding a language to the list of available languages for spell check, this was performing a spread operation on the language (introduced in #1723), thereby saving each letter separately. This caused invalid language codes to be saved. Simply removing the spread operator on `language` fixes this.
Fixes #1727.

Fix concatenation of spell check languages

---

css/new-design/browser.css

Classes have changed a bit. This patch hides names in chat when private mode is enabled.
Closes: #1732

Fix names in private mode

---

source/browser.ts

The settings menu selector was changed so the hide-preferences-window class was added but not removed which broke all modal windows including image view.
Closes: #1751

Fix modal windows

---

package-lock.json
package.json

In electron-builder there is an [issue with publishing snap packages](https://github.com/electron-userland/electron-builder/issues/6327) on version that is currently used in CI (22.13.1). This is fixed in eb 22.14.5. Only bumping the version fixes this issue. Since snap packages have not been published for past few version, this didn't affect Caprine.

Bump electron-builder version

---

css/new-design/browser.css

This should fix the problem with search bar showing in compact mode (at least until the class list changes again).
Fixes #1780

Fix css selectors to hide search in compact mode

---

source/browser/conversation-list.ts

Notifications have not been working since the redesign (Workaround for #1562). This PR aims to work around this missing functionality.
The message sidebar changes to show the unread dot when a new message is received. A mutation event listener has been added to watch for this new blue dot. When the dot appears, we can obtain the message content, message author, and profile picture of the chat and send a notification using existing notification functions.
The downside with this workaround is that there is no notification when multiple new messages are received in the same chat (when the blue dot already exists and a new message is received). However, I believe just having some notification is far better than the current status of not having any notification.
There were also a couple of …

Workaround for notifications

---

source/browser.ts

On Linux with fontconfig, the system font for emoji is the "emoji" font rather than "system-ui" [1-2]. When using the system-ui font on standard configurations, it falls back to using "sans-serif" before the emoji font, in my case Arimo before Noto Color Emoji:
```bash
$ fc-match system-ui
Arimo-Regular.ttf: "Arimo" "Regular"
```
This presents a problem for emoji characters which are included as monochrome unicode glyphs in the sans-serif font (such as the smiley face ☺), since these are rendered with the monochrome characters from sans-serif rather than the emoji font. This patch makes use of the emoji alias shipped by default in fontconfig on Linux systems to preferentially use the system emoji font.
[1] https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/main/conf.d/45-generic.c …

Use 'emoji' font alias on Linux for system emoji

---

css/new-design/dark-mode.css

Also affects Preferences (but doesn't actually need the custom CSS any more). The "new message" button, however, is `[role='link']`.

Fix dark button for New Room

---

source/browser/conversation-list.ts

A fix for system notifications post-redesign (#1562) was merged (#1739).
A change in Messenger has caused a null element causing the notification workaround to no longer function.
This will now verify that the element is not null before attempting to use its properties, no longer resulting in an exception and allowing the notification functionality to function as intended again.

Fix workaround for notifications

---

css/new-design/dark-mode.css

becomes
This also applies to the audio call icons.
Fixes #1840.

Dark mode fixes

---

source/browser.ts

Added functionality to select negatively indexed menu items, since "Log out" is always last in the menu item list.
[Selecting item 11 broke when another "New! Messenger for Windows" item was added to the list. I think that "Log out" will stay as the last item, so this should be more future-proof, but we'll see what the Messenger backend devs do.]

Select log out as last menu item

---

package.json

Release publishing was broken since snap target was not removed from electron-builder config. This should stop the building of snap and thus fix the publishing.
Closes: #1848

Fix release publishing

---

.github/workflows/main.yml
package.json

I have access to the snap package on the snap store and have managed to manually publish the latest version. I however don't have access to change the access token for ci so I will either need that access in this repo or I could send Sindre the token somehow so he can add it himself.
// @sindresorhus

Restore snap publishing

---

.github/workflows/main.yml

After building on every commit, ci tried to make a github release. It fails since it's not the release commit (it can't upload over already existing packages). Only on tagged commits (release commits) should the packages be published.
In addition, Node.js version has been bumped in CI.

Fix ci build step

---

source/menu.ts

Adds maintainers' names in the about dialog (Help -> About Caprine). Resolves #1873.
A text parameter I found in electron-util is used to store the text. However, this should only be temporary as the about dialog in general needs to be improved.

Add maintainers in about dialog

---

source/browser.ts
source/browser/conversation-list.ts

Old design was deprecated more than a year ago by Facebook.
Why have redundant code that does nothing and conditions (for new design) that always return true? This PR removes some of the old code but not everything. There is a lot going on under the hood and a followup PR might be needed.
Open for discussion.

Remove code related to old design

---

source/index.ts

I have noticed that by default, messenger.com overrides the window title and sets it to "Messenger". Wouldn't it be better if it was set to "Caprine"?

Set window title to "Caprine"

---

source/menu.ts

Default file for custom css contained color scheme variables for old design. This caused some confusion which lead to users thinking the custom styles didn't load. I'm proposing a fix which is just removing those variables. Users can create a custom color scheme by copying css variables from Messenger website and putting them in custom css file and modifying them.
Closes: #1900

Fix custom css default file

---

.gitignore
package.json
readme.md

This patch adds Apple Silicon support.
Electron Updater compatibility version is bumped because of this [issue](https://github.com/electron-userland/electron-builder/issues/5689). In the long run we should probably switch to Electron Forge.
Closes: #1975

Add Apple Silicon support

---

packages/rpm/caprine.spec

When trying to install caprine I got:
```
Error: Transaction test error:
file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of caprine-2.57.0-1.fc37.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of caprine-2.57.0-1.fc37.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of caprine-2.57.0-1.fc37.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of caprine-2.57.0-1.fc37.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
```
According to …

Exclude /usr/lib/.build-id/ from generated package

---

source/autoplay.ts
source/browser.ts
source/config.ts
source/emoji.ts
source/index.ts

This patch removes use of [electron-store](https://github.com/sindresorhus/electron-store) package from renderer process. For some reason, today electron-store decided to cause trouble (specifically its dependency, [ajv](https://github.com/ajv-validator/ajv)) in the renderer process so using IPC calls, I've moved all its use-cases to the main process.
Closes: #2036

Workaround for electron-store in renderer

---

source/browser.ts
source/browser/selectors.ts

There's a recent issue where no dialog is displayed(related to pr #2006). This pr updates the preferences selectors, and also changes the `closePreferences` function to properly remove the `hide-preferences-window` class, when the preferences overlay is closed.
Fixes #2055
Fixes #2054

Hidden dialogue fix

---

source/browser/conversation-list.ts
source/browser/selectors.ts
source/index.ts

Hello this is a fix for the tray icon/indicator issue. After running the tests, I got an error about putting await inside of a loop. So unfortunately, I had to change the selector of the sidebar and remove the loop.
Partially fixes #1825 (this wouldn't implement notifications).
Fixes #1995
Fixes #1823
Fixes #2031

Tray icon/indicator Fix

---

css/dark-mode.css

Minor dark mode change to "Privacy & safety" item in Messenger settings
fixed to

Apply dark mode coloring to Privacy & safety in settings

---

css/dark-mode.css

The previous selector (`.x14hiurz`) was not specific enough for the search results "Close" button, since it also affected preferences selectors below.
The color is updated so the "Close" actually looks like a clickable button and no longer affects the preferences checkboxes.
(I think I'd like *more* contrast on the checkboxes from a design perspective, but am reverting to default styles for now.)

Use more specific  CSS selector for Search results Close button

---

source/browser.ts
source/browser/selectors.ts
source/menu.ts

I'm not sure if it's safe to assume that (most) people have the new sidebar at this point, or if we should retain past compatibility. This should allow for selecting view through the View menu, if users want to select it that way.
I renamed the actions to reflect what Messenger calls the different views as well.
I am very open to any suggestions about how this should be handled or adjusted as needed.
Fixes #1984.

Select views for new sidebar

---

source/browser.ts

Since the notifications are currently somewhat broken, this is a temporary patch that returns `false` if the selector is null. I would be wary of simply toggling the "Do not disturb" mode, since it normally sets a time limit for that mode, which may require more of an overhaul of notification options. I'm open to handling this differently, but it does handle this promise/error.
The error on the current version:
```
(node:10656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'checked')
at ...\caprine\dist-js\browser.js:208:34
at async EventEmitter.listener (...\caprine\node_modules\electron-better-ipc\source\renderer.js:46:34)
```

Verify that notificationCheckbox is non-null

---

source/browser/selectors.ts

The left sidebar's class has been changed. As a consequence, the tray icon indicator is not working.

Update left sidebar selector

---

package-lock.json
package.json

Electron 24 is EOL. This patch bumps Electron to 26 and also the `@electron/remote` module so it's compatible with new Electron version.

Bump Electron version

---

css/browser.css

These selectors work on both Mac and Windows for both the chat list and settings list.

Update Messenger for Mac/Windows selectors

---

source/browser/selectors.ts

The tray icon does not change when there are unread messages. This is due to the broken chatsIcon selector.

Tray icon Fix

---

css/browser.css

Apply Chats title margin for MacOS only

---

source/browser/conversation-list.ts

This will loop through _all_ the chat categories (Chats, People, Marketplace, Message Requests, Archive) and extract any numbers in its `ariaLabel`. While I don't expect People or Archive to have unread items, this will still loop through them. This is built off of discussion in #2109 with @stkrknds and @sgtcoder.
_Technically,_ the `elementReady()` only waits for the first element (Chats), but it still seems to work as expected after startup.
One strange thing: if you have unread Marketplace messages when Caprine starts up, it won't load this number until Marketplace is selected. But this is an issue with Messenger.com itself, not with Caprine.

Include Marketplace and other unread messages in tray icon number

---

css/dark-mode.css
package.json
source/autoplay.ts
source/browser.ts
source/browser/conversation-list.ts
source/config.ts
source/conversation.d.ts
source/emoji.ts
source/index.ts
source/menu-bar-mode.ts
source/menu.ts
source/notification-event.d.ts
source/notifications-isolated.ts
source/notifications.d.ts
source/tray.ts
source/types.ts
source/util.ts

Recent chore (d1b2e14b17ae0ec6a75d47967a24c891c481199d) upgraded some dependency versions, which required some `xo` and `stylelint` rule exceptions to be added. I reverted most of the rule exceptions that were added and cleaned up the code that was breaking the rules.

Lint fixes from recent dependency bumps

---

css/dark-mode.css

These CSS changes are no longer necessary. Most of them are not even selectors on the page any more. I tested these one at a time and couldn't see any changes visually and checked for the selectors too.
Fixes #2180.
Fixes #2194.

Remove unnecessary Dark Mode CSS

---

source/browser.ts
source/browser/selectors.ts

Using "role=navigation" is no longer unique enough to get the view menu. This led to 7 match results (at least in my case) for `'[role=navigation] > div > div'`, which defaults to the `selectMenuItem()` use case.
[The users' interfaces seem to be more unified now, so we could consider eliminating the "new sidebar" checks too, since those may be artifacts from multiple versions ago.]
Fixes #2178.

Update selector for chat view menu

---

css/browser.css
source/browser.ts
source/menu.ts

The "Active Contacts" view and menu option has been removed from the website's interface, so this is updating the app's view section options.
This builds on #2182, since it relies on the sidebar selector.

Remove Active Contacts view

---

css/browser.css
source/browser.ts
source/browser/selectors.ts
source/menu.ts

This fixes most of the selected conversation controls as well as the search functionality within a conversation.
The archive and delete functions need to be negative, since there are slightly different menus if a conversation is encrypted or not (usually if there's a separate encrypted conversation), but the end of the menus are the same. (Not sure why this distinction still exists...)
Already encrypted:
Can start encrypted chat:
Fixes #2185.

Fix Conversation Controls and Search Function

---

source/browser.ts
source/browser/selectors.ts

The selector that was previously used is also used for Security Alerts (including entering in your message sync PIN) and other windows, so it would be difficult to use that style of selector. Using `aria-label=Preferences` seems to be the best way to address this.
The current method used `elementReady()` on the first element that matched, which was usually the Sync PIN window, which caused some other conflicts with how the typical code flow would work.
The extra "style" code is no longer necessary with the backend design changes. (It's probably been outdated for some time...)
Fixes #2167.

Use aria-label for Preferences selector

---

source/browser.ts
source/browser/selectors.ts

Using `aria-label` had localization issues that did not work in non-English locales. Using the `class` info is necessary to work across locales. The `:has()` is necessary since the specified parent class is used for all windows (restore chat PIN, other settings windows, etc.).
The selector is likely still fragile due to the amount of back-end changes that are typically made, so I restored the comment.
Fixes #2167.

Use preferences window class info instead of aria-label
